package com.nxtlife.mgs.util;

public final class AuthorityUtils {

	/**
	 * AUTHORITY TO FETCH AUTHORITY
	 */
	public static final String AUTHORITY_FETCH = "ROLE_AUTHORITY_FETCH";

	/**
	 * AUTHORITY TO FETCH ROLE
	 */
	public static final String ROLE_FETCH = "ROLE_ROLE_FETCH";

	/**
	 * AUTHORITY TO CREATE ROLE
	 */
	public static final String ROLE_CREATE = "ROLE_ROLE_CREATE";

	/**
	 * AUTHORITY TO UPDATE ROLE
	 */
	public static final String ROLE_UPDATE = "ROLE_ROLE_UPDATE";

	/**
	 * AUTHORITY TO DELETE ROLE
	 */
	public static final String ROLE_DELETE = "ROLE_ROLE_DELETE";

	/**
	 * AUTHORITY TO FETCH USER
	 */
	public static final String USER_FETCH = "ROLE_USER_FETCH";

	/**
	 * AUTHORITY TO CREATE USER
	 */
	public static final String USER_CREATE = "ROLE_USER_CREATE";

	/**
	 * AUTHORITY TO UPDATE USER
	 */
	public static final String USER_UPDATE = "ROLE_USER_UPDATE";

	/**
	 * AUTHORITY TO DELETE USER
	 */
	public static final String USER_DELETE = "ROLE_USER_DELETE";

	/**
	 * AUTHORITY TO ADD SCHOOL
	 */
	public static final String SCHOOL_CREATE = "ROLE_SCHOOL_CREATE";

	/**
	 * AUTHORITY TO UPDATE SCHOOL
	 */
	public static final String SCHOOL_UPDATE = "ROLE_SCHOOL_UPDATE";
	
	/**
	 * AUTHORITY TO VIEW SCHOOL
	 */
	public static final String SCHOOL_VIEW = "ROLE_SCHOOL_VIEW";

	/**
	 * AUTHORITY TO DELETE SCHOOL
	 */
	public static final String SCHOOL_DELETE = "ROLE_SCHOOL_DELETE";

	/**
	 * AUTHORITY TO ADD SCHOOL STAKEHOLDER
	 */
	public static final String SCHOOL_STAKEHOLDER_CREATE = "ROLE_SCHOOL_STAKEHOLDER_CREATE";

	/**
	 * AUTHORITY TO UPDATE SCHOOL STAKEHOLDER
	 */
	public static final String SCHOOL_STAKEHOLDER_UPDATE = "ROLE_SCHOOL_STAKEHOLDER_UPDATE ";

	/**
	 * AUTHORITY TO DELETE SCHOOL STAKEHOLDER
	 */
	public static final String SCHOOL_STAKEHOLDER_DELETE = "ROLE_SCHOOL_STAKEHOLDER_DELETE ";

	/**
	 * AUTHORITY TO VIEW SCHOOL STAKEHOLDER
	 */
	public static final String SCHOOL_STAKEHOLDER_READ = "ROLE_SCHOOL_STAKEHOLDER_VIEW ";

	/**
	 * AUTHORITY TO ADD SCHOOL ACTIVITY
	 */
	public static final String SCHOOL_ACTIVITY_CREATE = "ROLE_SCHOOL_ACTIVITY_CREATE";

	/**
	 * AUTHORITY TO UPDATE SCHOOL ACTIVITY
	 */
	public static final String SCHOOL_ACTIVITY_UPDATE = "ROLE_SCHOOL_ACTIVITY_UPDATE ";

	/**
	 * AUTHORITY TO DELETE SCHOOL ACTIVITY
	 */
	public static final String SCHOOL_ACTIVITY_DELETE = "ROLE_SCHOOL_ACTIVITY_DELETE ";
	
	/**
	 * AUTHORITY TO VIEW SCHOOL ACTIVITY
	 */
	public static final String SCHOOL_ACTIVITY_VIEW = "ROLE_SCHOOL_ACTIVITY_VIEW ";
	
	/**
	 * AUTHORITY TO ADD SCHOOL PERFORMED_ACTIVITY
	 */
	public static final String SCHOOL_PERFORMED_ACTIVITY_CREATE = "ROLE_SCHOOL_PERFORMED_ACTIVITY_CREATE";

	/**
	 * AUTHORITY TO UPDATE SCHOOL PERFORMED_ACTIVITY
	 */
	public static final String SCHOOL_PERFORMED_ACTIVITY_UPDATE = "ROLE_SCHOOL_PERFORMED_ACTIVITY_UPDATE ";

	/**
	 * AUTHORITY TO DELETE SCHOOL PERFORMED_ACTIVITY
	 */
	public static final String SCHOOL_PERFORMED_ACTIVITY_DELETE = "ROLE_SCHOOL_PERFORMED_ACTIVITY_DELETE ";
	
	/**
	 * AUTHORITY TO VIEW SCHOOL PERFORMED_ACTIVITY
	 */
	public static final String SCHOOL_PERFORMED_ACTIVITY_VIEW = "ROLE_SCHOOL_PERFORMED_ACTIVITY_VIEW ";
	
	/**
	 * AUTHORITY TO REVIEW SCHOOL PERFORMED_ACTIVITY
	 */
	public static final String SCHOOL_PERFORMED_ACTIVITY_REVIEW = "ROLE_SCHOOL_PERFORMED_ACTIVITY_REVIEW ";
	
	/**
	 * AUTHORITY TO ADD SCHOOL_CLUB_MEMBERSHIP
	 */
	public static final String SCHOOL_CLUB_MEMBERSHIP_CREATE = "ROLE_SCHOOL_CLUB_MEMBERSHIP_CREATE";

	/**
	 * AUTHORITY TO UPDATE SCHOOL_CLUB_MEMBERSHIP
	 */
	public static final String SCHOOL_CLUB_MEMBERSHIP_UPDATE = "ROLE_SCHOOL_CLUB_MEMBERSHIP_UPDATE ";
	/**
	 * AUTHORITY TO VIEW SCHOOL_CLUB_MEMBERSHIP
	 */
	public static final String SCHOOL_CLUB_MEMBERSHIP_VIEW = "ROLE_SCHOOL_CLUB_MEMBERSHIP_VIEW ";

	/**
	 * AUTHORITY TO ASSIGN OR REMOVE SCHOOL ACTIVITY TO COACHES
	 */
	public static final String SCHOOL_ACTIVITY_ASSIGN = "ROLE_SCHOOL_ACTIVITY_ASSIGN ";

	/**
	 * AUTHORITY TO UPDATE SCHOOL FACULTY PROFILE 
	 */
	public static final String SCHOOL_FACULTY_PROFILE_UPDATE = "ROLE_SCHOOL_FACULTY_PROFILE_UPDATE ";

	/**
	 * AUTHORITY TO UPDATE SCHOOL STUDENT PROFILE 
	 */
	public static final String SCHOOL_STUDENT_PROFILE_UPDATE = "ROLE_SCHOOL_STUDENT_PROFILE_UPDATE ";

	/**
	 * AUTHORITY TO DELETE SCHOOL FACULTY PROFILE 
	 */
	public static final String SCHOOL_FACULTY_DELETE = "ROLE_SCHOOL_FACULTY_DELETE ";
	/**
	 * AUTHORITY TO DELETE SCHOOL STUDENT PROFILE 
	 */

	public static final String SCHOOL_STUDENT_DELETE = "ROLE_SCHOOL_STUDENT_DELETE ";

	/**
	 * AUTHORITY TO VIEW SCHOOL STUDENT PROFILE 
	 */

	public static final String SCHOOL_FACULTY_VIEW = "ROLE_SCHOOL_FACULTY_VIEW ";

	/**
	 * AUTHORITY TO VIEW SCHOOL STUDENT PROFILE 
	 */
	public static final String SCHOOL_STUDENT_VIEW = "ROLE_SCHOOL_STUDENT_VIEW ";
	
	/**
	 * AUTHORITY TO VIEW SCHOOL STUDENT CERTIFICATE VIEW  
	 */
	public static final String SCHOOL_STUDENT_CERTIFICATE_VIEW = "ROLE_SCHOOL_STUDENT_CERTIFICATE_VIEW ";
	/**
	 * AUTHORITY TO CREATE SCHOOL  STUDENT CERTIFICATE CREATE  
	 */
	public static final String SCHOOL_STUDENT_CERTIFICATE_ADD = "ROLE_SCHOOL_STUDENT_CERTIFICATE_ADD ";
	/**
	 * AUTHORITY TO ADD SCHOOL SESSION
	 */
	public static final String SCHOOL_SESSION_CREATE = "ROLE_SCHOOL_SESSION_CREATE";

	/**
	 * AUTHORITY TO UPDATE SCHOOL SESSION
	 */
	public static final String SCHOOL_SESSION_UPDATE = "ROLE_SCHOOL_SESSION_UPDATE ";

	/**
	 * AUTHORITY TO DELETE SCHOOL SESSION
	 */
	public static final String SCHOOL_SESSION_DELETE = "ROLE_SCHOOL_SESSION_DELETE ";
	/**
	 * AUTHORITY TO VIEW SCHOOL SESSION
	 */
	public static final String SCHOOL_SESSION_VIEW = "ROLE_SCHOOL_SESSION_VIEW ";
	/**
	 * AUTHORITY TO ADD SCHOOL AWARD
	 */
	public static final String SCHOOL_AWARD_CREATE = "ROLE_SCHOOL_AWARD_CREATE";

	/**
	 * AUTHORITY TO DELETE SCHOOL AWARD
	 */
	public static final String SCHOOL_AWARD_DELETE = "ROLE_SCHOOL_AWARD_DELETE ";
	
	/**
	 * AUTHORITY TO VIEW SCHOOL AWARD
	 */
	public static final String SCHOOL_AWARD_VIEW = "ROLE_SCHOOL_AWARD_VIEW ";
	
	/**
	 * AUTHORITY TO REVIEW(APPROVE / REJECT) SCHOOL AWARD
	 */
	public static final String SCHOOL_AWARD_REVIEW = "ROLE_SCHOOL_AWARD_REVIEW ";
}
